/*******************************************************************************
 * Copyright (c) 2005-2011 eBay Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. VjCommentConstants.java */
package org.ebayopensource.dsf.jstojava.parser.comments;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VjCommentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PUBLIC = 3;
  /** RegularExpression Id. */
  int PRIVATE = 4;
  /** RegularExpression Id. */
  int ATR = 5;
  /** RegularExpression Id. */
  int ANNOTATION = 6;
  /** RegularExpression Id. */
  int PROTECTED = 7;
  /** RegularExpression Id. */
  int FINAL = 8;
  /** RegularExpression Id. */
  int STATIC = 9;
  /** RegularExpression Id. */
  int DYNAMIC = 10;
  /** RegularExpression Id. */
  int NEEDS = 11;
  /** RegularExpression Id. */
  int TYPEREF = 12;
  /** RegularExpression Id. */
  int TYPEREF_OLD = 13;
  /** RegularExpression Id. */
  int LP = 14;
  /** RegularExpression Id. */
  int RP = 15;
  /** RegularExpression Id. */
  int LCB = 16;
  /** RegularExpression Id. */
  int RCB = 17;
  /** RegularExpression Id. */
  int LB = 18;
  /** RegularExpression Id. */
  int RB = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int GT = 21;
  /** RegularExpression Id. */
  int LT = 22;
  /** RegularExpression Id. */
  int QUESTIONMARK = 23;
  /** RegularExpression Id. */
  int EXTENDS = 24;
  /** RegularExpression Id. */
  int SUPER = 25;
  /** RegularExpression Id. */
  int ABSTRACT = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int COLON = 28;
  /** RegularExpression Id. */
  int DOUBLE_COLON = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int CARET = 31;
  /** RegularExpression Id. */
  int TYPE = 32;
  /** RegularExpression Id. */
  int LITERAL = 33;
  /** RegularExpression Id. */
  int DOTDOTDOT = 34;
  /** RegularExpression Id. */
  int LETTER = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int PERIOD = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"public\"",
    "\"private\"",
    "\"@\"",
    "<ANNOTATION>",
    "\"protected\"",
    "\"final\"",
    "\"static\"",
    "\"dynamic\"",
    "\"needs\"",
    "\"type::\"",
    "\"Type::\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\"extends\"",
    "\"super\"",
    "\"abstract\"",
    "\",\"",
    "\":\"",
    "\"::\"",
    "\";\"",
    "\"^\"",
    "<TYPE>",
    "<LITERAL>",
    "<DOTDOTDOT>",
    "<LETTER>",
    "<DIGIT>",
    "\".\"",
  };

}
