vjo.ctype("org.ebayopensource.dsf.jst.validation.vjo.BugFixes.Bug5880")
.protos({
	"private": "property", 
	"boolean": "property", 
	"abstract": "property", 
	"implements": "property", 
	"protected": "property", 
	"throws": "property", 
	"double": "property",
	"import": "property",
	"public": "property",
	"byte": "property",
	"transient": "property",
	"extends": "property",
	"int": "property",
	"short": "property",
	"final": "property",
	"interface": "property",
	"static": "property",
	"char": "property",
	"long": "property",
	"strictfp": "property",
	"volatile": "property",
	"class": "property",
	"float": "property",
	"native": "property",
	"super": "property",
	"const": "property",
	"package": "property",
	"synchronized": "property"
})
.endType();