vjo.ctype('syntax.unique.javaKeyWord1')
.protos({
abstract : "String", //< public String 
default : "String", //< public String 
if : "String", //< public String 
private : "String", //< public String 
this : "String", //< public String 
boolean : "String", //< public String 
do : "String", //< public String 
implements : "String", //< public String 
protected : "String", //< public String 
throw : "String", //< public String 
break : "String", //< public String 
double : "String", //< public String 
import : "String", //< public String 
public : "String", //< public String 
throws : "String", //< public String 
byte : "String", //< public String 
else : "String", //< public String 
instanceof : "String", //< public String 
return : "String", //< public String 
transient : "String", //< public String 
case : "String", //< public String 
extends : "String", //< public String 
int : "String", //< public String 
short : "String", //< public String 
try : "String", //< public String 
catch : "String", //< public String 
final : "String", //< public String 
interface : "String", //< public String 
static : "String", //< public String 
void : "String", //< public String 
char : "String", //< public String 
finally : "String", //< public String 
long : "String", //< public String 
strictfp : "String", //< public String 
volatile : "String", //< public String 
class : "String", //< public String 
float : "String", //< public String 
native : "String", //< public String 
super : "String", //< public String 
while : "String", //< public String 
const : "String", //< public String 
for : "String", //< public String 
new : "String", //< public String 
switch : "String", //< public String 
continue : "String", //< public String 
goto : "String", //< public String 
package : "String", //< public String 
synchronized : "String" //< public String 
})
.endType();