vjo.ctype('syntax.unique.jsKeyWord1')
.protos({
     break : "String", //< public String 
     delete : "String", //< public String 
     function : "String", //< public String 
     return : "String", //< public String 
     typeof : "String", //< public String 
     case : "String", //< public String 
     do : "String", //< public String 
     if : "String", //< public String 
     switch : "String", //< public String 
     var : "String", //< public String 
     catch : "String", //< public String 
     else : "String", //< public String 
     in : "String", //< public String 
     this : "String", //< public String 
     void : "String", //< public String 
     continue : "String", //< public String 
     false : "String", //< public String 
     instanceof : "String", //< public String 
     throw : "String", //< public String 
     while : "String", //< public String 
     debugger : "String", //< public String 
     finally : "String", //< public String 
     new : "String", //< public String 
     true : "String", //< public String 
     with : "String", //< public String 
     default : "String", //< public String 
     for : "String", //< public String 
     null : "String", //< public String 
     try : "String", //< public String 
     abstract : "String", //< public String 
     double : "String", //< public String 
     goto : "String", //< public String 
     native : "String", //< public String 
     static : "String", //< public String 
     boolean : "String", //< public String 
     enum : "String", //< public String 
     implements : "String", //< public String 
     package : "String", //< public String 
     super : "String", //< public String 
     byte : "String", //< public String 
     export : "String", //< public String 
     import : "String", //< public String 
     private : "String", //< public String 
     synchronized : "String", //< public String 
     char : "String", //< public String 
     extends : "String", //< public String 
     int : "String", //< public String 
     protected : "String", //< public String 
     throws : "String", //< public String 
     class : "String", //< public String 
     final : "String", //< public String 
     interface : "String", //< public String 
     public : "String", //< public String 
     transient : "String", //< public String 
     const : "String", //< public String 
     float : "String", //< public String 
     long : "String", //< public String 
     short : "String", //< public String 
     volatile : "String", //< public String 
     arguments : "String", //< public String 
     encodeURI : "String", //< public String 
     Infinity : "String", //< public String 
     Object : "String", //< public String 
     String : "String", //< public String 
     Array : "String", //< public String 
     Error : "String", //< public String 
     isFinite : "String", //< public String 
     parseFloat : "String", //< public String 
     SyntaxError : "String", //< public String 
     Boolean : "String", //< public String 
     escape : "String", //< public String 
     isNaN : "String", //< public String 
     parseInt : "String", //< public String 
     TypeError : "String", //< public String 
     Date : "String", //< public String 
     eval : "String", //< public String 
     Math : "String", //< public String 
     RangeError : "String", //< public String 
     undefined : "String", //< public String 
     decodeURI : "String", //< public String 
     EvalError : "String", //< public String 
     NaN : "String", //< public String 
     ReferenceError : "String", //< public String 
     unescape : "String", //< public String 
     decodeURICompo : "String", //< public String 
     Function : "String", //< public String 
     Number : "String", //< public String 
     RegExp : "String", //< public String 
     URIError : "String" //< public String 
})
.endType();