/*******************************************************************************
 * Copyright (c) 2005-2011 eBay Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. SacParserConstants.java */
package org.ebayopensource.dsf.css.parser;

public interface SacParserConstants {

  int EOF = 0;
  int S = 1;
  int LBRACE = 5;
  int RBRACE = 6;
  int COMMA = 7;
  int DOT = 8;
  int SEMICOLON = 9;
  int COLON = 10;
  int ASTERISK = 11;
  int SLASH = 12;
  int PLUS = 13;
  int MINUS = 14;
  int UNDERBAR = 15;
  int EQUALS = 16;
  int GT = 17;
  int LSQUARE = 18;
  int RSQUARE = 19;
  int TILDE = 20;
  int VERTICAL = 21;
  int HASH = 22;
  int STRING = 23;
  int RROUND = 24;
  int URL = 25;
  int URI = 26;
  int CDO = 27;
  int CDC = 28;
  int INCLUDES = 29;
  int DASHMATCH = 30;
  int STARTS_WITH = 31;
  int ENDS_WITH = 32;
  int CONTAINS_AT_LEAST_ONE = 33;
  int IMPORT_SYM = 34;
  int PAGE_SYM = 35;
  int MEDIA_SYM = 36;
  int WEBKIT_KEYFRAMES_SYM = 37;
  int FONT_FACE_SYM = 38;
  int CHARSET_SYM = 39;
  int NAMESPACE_SYM = 40;
  int ATKEYWORD = 41;
  int IMPORTANT_SYM = 42;
  int INHERIT = 43;
  int EMS = 44;
  int EXS = 45;
  int LENGTH_PX = 46;
  int LENGTH_CM = 47;
  int LENGTH_MM = 48;
  int LENGTH_IN = 49;
  int LENGTH_PT = 50;
  int LENGTH_PC = 51;
  int ANGLE_DEG = 52;
  int ANGLE_RAD = 53;
  int ANGLE_GRAD = 54;
  int TIME_MS = 55;
  int TIME_S = 56;
  int FREQ_HZ = 57;
  int FREQ_KHZ = 58;
  int DIMEN = 59;
  int PERCENTAGE = 60;
  int NUMBER = 61;
  int RGB = 62;
  int RGBA = 63;
  int HSL = 64;
  int HSLA = 65;
  int IDENT = 66;
  int MINUS_UNDERBAR_COMBO = 67;
  int EXTENDED_IDENT = 68;
  int NAMESPACE_IDENT = 69;
  int EMPTY_NAMESPACE_IDENT = 70;
  int STAR_NAMESPACE_IDENT = 71;
  int NAMESPACE_STAR = 72;
  int FUNCTION = 73;
  int EXTENDED_IDENT_FUNCTION = 74;
  int NAME = 75;
  int NUM = 76;
  int UNICODERANGE = 77;
  int RANGE = 78;
  int Q16 = 79;
  int Q15 = 80;
  int Q14 = 81;
  int Q13 = 82;
  int Q12 = 83;
  int Q11 = 84;
  int PNMSTART = 85;
  int NMSTART = 86;
  int NMCHAR = 87;
  int STRING1 = 88;
  int STRING2 = 89;
  int NONASCII = 90;
  int ESCAPE = 91;
  int NL = 92;
  int UNICODE = 93;
  int HNUM = 94;
  int H = 95;
  int UNKNOWN = 96;

  int DEFAULT = 0;
  int COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 4>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"_\"",
    "\"=\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "\"~\"",
    "\"|\"",
    "<HASH>",
    "<STRING>",
    "\")\"",
    "<URL>",
    "<URI>",
    "\"<!--\"",
    "\"-->\"",
    "\"~=\"",
    "\"|=\"",
    "\"^=\"",
    "\"$=\"",
    "\"*=\"",
    "\"@import\"",
    "\"@page\"",
    "\"@media\"",
    "\"@-webkit-keyframes\"",
    "\"@font-face\"",
    "\"@charset\"",
    "\"@namespace\"",
    "<ATKEYWORD>",
    "<IMPORTANT_SYM>",
    "\"inherit\"",
    "<EMS>",
    "<EXS>",
    "<LENGTH_PX>",
    "<LENGTH_CM>",
    "<LENGTH_MM>",
    "<LENGTH_IN>",
    "<LENGTH_PT>",
    "<LENGTH_PC>",
    "<ANGLE_DEG>",
    "<ANGLE_RAD>",
    "<ANGLE_GRAD>",
    "<TIME_MS>",
    "<TIME_S>",
    "<FREQ_HZ>",
    "<FREQ_KHZ>",
    "<DIMEN>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "\"rgb(\"",
    "\"rgba(\"",
    "\"hsl(\"",
    "\"hsla(\"",
    "<IDENT>",
    "<MINUS_UNDERBAR_COMBO>",
    "<EXTENDED_IDENT>",
    "<NAMESPACE_IDENT>",
    "<EMPTY_NAMESPACE_IDENT>",
    "<STAR_NAMESPACE_IDENT>",
    "<NAMESPACE_STAR>",
    "<FUNCTION>",
    "<EXTENDED_IDENT_FUNCTION>",
    "<NAME>",
    "<NUM>",
    "<UNICODERANGE>",
    "<RANGE>",
    "<Q16>",
    "<Q15>",
    "<Q14>",
    "<Q13>",
    "<Q12>",
    "\"?\"",
    "<PNMSTART>",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRING1>",
    "<STRING2>",
    "<NONASCII>",
    "<ESCAPE>",
    "<NL>",
    "<UNICODE>",
    "<HNUM>",
    "<H>",
    "<UNKNOWN>",
  };

}
