/*******************************************************************************
 * Copyright (c) 2005-2011 eBay Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. SacParser.java */
package org.ebayopensource.dsf.css.parser;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.ebayopensource.dsf.css.parser.selectors.DConditionFactory;
import org.ebayopensource.dsf.css.parser.selectors.DSelectorFactory;
import org.ebayopensource.dsf.css.sac.CssException;
import org.ebayopensource.dsf.css.sac.CssParseException;
import org.ebayopensource.dsf.css.sac.ICondition;
import org.ebayopensource.dsf.css.sac.IConditionFactory;
import org.ebayopensource.dsf.css.sac.IDocumentHandler;
import org.ebayopensource.dsf.css.sac.IErrorHandler;
import org.ebayopensource.dsf.css.sac.InputSource;
import org.ebayopensource.dsf.css.sac.ILexicalUnit;
import org.ebayopensource.dsf.css.sac.ILocator;
import org.ebayopensource.dsf.css.sac.IParser;
import org.ebayopensource.dsf.css.sac.ISelector;
import org.ebayopensource.dsf.css.sac.ISelectorFactory;
import org.ebayopensource.dsf.css.sac.ISelectorList;
import org.ebayopensource.dsf.css.sac.ISimpleSelector;

// TODO: after parser code generation, do these items (these cannot be done in the .jj grammar file):
// - clean up warnings in SacParserTokenManager
// - comment out this line:
//   private boolean jj_semLA;
// - change this line:
//   private java.util.Vector jj_expentries = new java.util.Vector();
// to this:
//   private List<int[]> jj_expentries = new ArrayList<int[]>();
// - and in the jj_add_error_token(int, int) method, change this:
//   for(java.util.Enumeration enum = jj_expentries.elements(); enum.hasMoreElements();) {
//     int[] oldentry = (int[])(enum.nextElement());
// to this:
//   for(int[] oldentry : jj_expentries) {
// - and this:
//   jj_expentries.addElement(jj_expentry);
// to this:
//   jj_expentries.add(jj_expentry);
// - and in the generateParseException() method, change this:
//   jj_expentries.removeAllElements();
// to this:
//   jj_expentries.clear();
// - and this:
//   jj_expentries.addElement(jj_expentry);
// to this:
//   jj_expentries.add(jj_expentry);
// - and this:
//   exptokseq[i] = (int[])jj_expentries.elementAt(i);
// to this:
//   exptokseq[i] = jj_expentries.get(i);
// - delete this TODO item

public class SacParser implements IParser, SacParserConstants {
    private InputSource m_source = null;
//    private Locale m_locale = null;
    private IDocumentHandler m_docHandler = null;
//    private DErrorHandler m_errHandler = null;
    private ISelectorFactory m_selectorFactory = new DSelectorFactory();
    private IConditionFactory m_conditionFactory = new DConditionFactory();
    private boolean m_quiet = true;
    private StringBuilder m_errorMessage = new StringBuilder();

    public SacParser() {
        this((CharStream) null);
    }

    public void setLocale(Locale locale) throws CssException {
//        m_locale = locale;
        // TODO: Search for requested locale
//        throw new DCssException(DCssException.SAC_NOT_SUPPORTED_ERR);
    }

    public void setDocumentHandler(IDocumentHandler handler) {
        m_docHandler = handler;
    }

    public void setSelectorFactory(ISelectorFactory selectorFactory) {
        m_selectorFactory = selectorFactory;
    }

    public void setConditionFactory(IConditionFactory conditionFactory) {
        m_conditionFactory = conditionFactory;
    }

    public void setErrorHandler(IErrorHandler handler) {
//        m_errHandler = handler;
    }

    public void parseStyleSheet(InputSource source) throws CssException, IOException {
        m_source = source;
        ReInit(getCharStream(source));
        try {
            styleSheet();
            assertError();
        } catch (ParseException e) {
            throw new CssException(CssException.SAC_SYNTAX_ERR, e.getMessage(), e);
        }
    }

    public void parseStyleSheet(String uri) throws CssException, IOException {
        parseStyleSheet(new InputSource(uri));
    }

    public void parseStyleDeclaration(InputSource source) throws CssException, IOException {
        m_source = source;
        ReInit(getCharStream(source));
        try {
            styleDeclaration();
            assertError();
        } catch (ParseException e) {
            throw new CssException(CssException.SAC_SYNTAX_ERR, e.getMessage(), e);
        }
    }

    public void parseRule(InputSource source) throws CssException, IOException {
        m_source = source;
        ReInit(getCharStream(source));
        try {
            styleSheetRuleSingle();
            assertError();
        } catch (ParseException e) {
            throw new CssException(CssException.SAC_SYNTAX_ERR, e.getMessage(), e);
        }
    }

    public String getParserVersion() {
        return "http://www.w3.org/TR/REC-CSS2";
    }

    public ISelectorList parseSelectors(InputSource source)
            throws CssException, IOException {
        m_source = source;
        ReInit(getCharStream(source));
        ISelectorList sl = null;
        try {
            sl = selectorList();
        } catch (ParseException e) {
            throw new CssException(CssException.SAC_SYNTAX_ERR, e.getMessage(), e);
        }
        return sl;
    }

    public ILexicalUnit parsePropertyValue(InputSource source)
            throws CssException, IOException {
        m_source = source;
        ReInit(getCharStream(source));
        ILexicalUnit lu = null;
        try {
            lu = expr();
        } catch (ParseException e) {
            throw new CssException(CssException.SAC_SYNTAX_ERR, e.getMessage(), e);
        }
        return lu;
    }

    public boolean parsePriority(InputSource source)
            throws CssException, IOException {
        m_source = source;
        ReInit(getCharStream(source));
        boolean b = false;
        try {
            b = prio();
        } catch (ParseException e) {
            throw new CssException(CssException.SAC_SYNTAX_ERR, e.getMessage(), e);
        }
        return b;
    }

    private void assertError() throws CssException{
        if (m_errorMessage.length() != 0) {
            String errorMsg = m_errorMessage.toString();
            throw new CssException(CssException.SAC_SYNTAX_ERR, errorMsg, null);
        }
    }

    private CharStream getCharStream(InputSource source)
            throws CssException, IOException {
        if (source.getCharacterStream() != null) {
            return new ASCII_CharStream(source.getCharacterStream(), 1, 1);
        } else {

            // TODO: Handle other sources
            return null;
        }
    }

    private ILocator getLocator() {
        return null;
    }

// stylesheet
//    : [ CHARSET_SYM S* STRING S* ';' ]?
//        [S|CDO|CDC]* [ import [S|CDO|CDC]* ]*
//        [ [ ruleset | media | keyframes | page | font_face ] [S|CDO|CDC]* ]*
//    ;
//
  final public void styleSheet() throws ParseException {
    try {
          m_docHandler.startDocument(m_source);
      styleSheetRuleList();
      jj_consume_token(0);
    } finally {
        m_docHandler.endDocument(m_source);
    }
  }

  final public void styleSheetRuleList() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CHARSET_SYM:
      charsetRule();
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
      case CDO:
      case CDC:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        jj_consume_token(S);
        break;
      case CDO:
        jj_consume_token(CDO);
        break;
      case CDC:
        jj_consume_token(CDC);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPORT_SYM:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      importRule();
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
        case CDO:
        case CDC:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_3;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          jj_consume_token(S);
          break;
        case CDO:
          jj_consume_token(CDO);
          break;
        case CDC:
          jj_consume_token(CDC);
          break;
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NAMESPACE_SYM:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_4;
      }
      namespaceRule();
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
      case COLON:
      case ASTERISK:
      case LSQUARE:
      case HASH:
      case PAGE_SYM:
      case MEDIA_SYM:
      case WEBKIT_KEYFRAMES_SYM:
      case FONT_FACE_SYM:
      case ATKEYWORD:
      case IDENT:
      case NAMESPACE_IDENT:
      case EMPTY_NAMESPACE_IDENT:
      case STAR_NAMESPACE_IDENT:
      case NAMESPACE_STAR:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
      case COLON:
      case ASTERISK:
      case LSQUARE:
      case HASH:
      case IDENT:
      case NAMESPACE_IDENT:
      case EMPTY_NAMESPACE_IDENT:
      case STAR_NAMESPACE_IDENT:
      case NAMESPACE_STAR:
        styleRule();
        break;
      case MEDIA_SYM:
        mediaRule();
        break;
      case WEBKIT_KEYFRAMES_SYM:
        keyframesRule();
        break;
      case PAGE_SYM:
        pageRule();
        break;
      case FONT_FACE_SYM:
        fontFaceRule();
        break;
      case ATKEYWORD:
        unknownRule();
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
        case CDO:
        case CDC:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_6;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          jj_consume_token(S);
          break;
        case CDO:
          jj_consume_token(CDO);
          break;
        case CDC:
          jj_consume_token(CDC);
          break;
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

//
// This is used by ASTStyleSheet.insertRule to parse a single rule
//
  final public void styleSheetRuleSingle() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CHARSET_SYM:
      charsetRule();
      break;
    case IMPORT_SYM:
      importRule();
      break;
    case NAMESPACE_SYM:
      namespaceRule();
      break;
    case DOT:
    case COLON:
    case ASTERISK:
    case LSQUARE:
    case HASH:
    case IDENT:
    case NAMESPACE_IDENT:
    case EMPTY_NAMESPACE_IDENT:
    case STAR_NAMESPACE_IDENT:
    case NAMESPACE_STAR:
      styleRule();
      break;
    case MEDIA_SYM:
      mediaRule();
      break;
    case WEBKIT_KEYFRAMES_SYM:
      keyframesRule();
      break;
    case PAGE_SYM:
      pageRule();
      break;
    case FONT_FACE_SYM:
      fontFaceRule();
      break;
    case ATKEYWORD:
      unknownRule();
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void charsetRule() throws ParseException {
    jj_consume_token(CHARSET_SYM);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_7;
      }
      jj_consume_token(S);
    }
    jj_consume_token(STRING);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_8;
      }
      jj_consume_token(S);
    }
    jj_consume_token(SEMICOLON);
  }

// namespace
//   : NAMESPACE_SYM S* [namespace_prefix S*]? [STRING|URI] S* ';' S* ;
// namespace_prefix
//   : IDENT ;
  final public void namespaceRule() throws ParseException {
    jj_consume_token(NAMESPACE_SYM);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_9;
      }
      jj_consume_token(S);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
      jj_consume_token(IDENT);
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    jj_consume_token(STRING);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_10;
      }
      jj_consume_token(S);
    }
    jj_consume_token(SEMICOLON);
  }

  final public void unknownRule() throws ParseException {
    String s;
    jj_consume_token(ATKEYWORD);
        s = skip();
        m_docHandler.ignorableAtRule(s);
  }

// import
//     : IMPORT_SYM S*
//     [STRING|URI] S* [ medium [ ',' S* medium]* ]? ';' S*
//     ;
//
  final public void importRule() throws ParseException {
    Token t;
    DSacMediaList ml = new DSacMediaList();
    jj_consume_token(IMPORT_SYM);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_11;
      }
      jj_consume_token(S);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
      t = jj_consume_token(STRING);
      break;
    case URI:
      t = jj_consume_token(URI);
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_12;
      }
      jj_consume_token(S);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
      mediaList(ml);
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
        m_docHandler.importStyle(unescape(t.image), ml, null);
  }

  final public void keyframesName() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
      jj_consume_token(IDENT);
      break;
    case STRING:
      jj_consume_token(STRING);
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

// keyframes
//
  final public void keyframesRule() throws ParseException {
    jj_consume_token(WEBKIT_KEYFRAMES_SYM);
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_13;
      }
      jj_consume_token(S);
    }
    keyframesName();

    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[23] = jj_gen;
        break label_14;
      }
      jj_consume_token(S);
    }
    jj_consume_token(LBRACE);
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_15;
      }
      jj_consume_token(S);
    }
    keyframesBlocks();
    jj_consume_token(RBRACE);
  }

  final public void keyframesBlocks() throws ParseException {
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PERCENTAGE:
      case IDENT:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_16;
      }
      keyframesBlock();
      label_17:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[26] = jj_gen;
          break label_17;
        }
        jj_consume_token(S);
      }
    }
  }

  final public void keyframesBlock() throws ParseException {
    keyframesSelector();
    jj_consume_token(LBRACE);
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[27] = jj_gen;
        break label_18;
      }
      jj_consume_token(S);
    }

    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
    case EXTENDED_IDENT:
      kfdeclaration();
      break;
    default:
      jj_la1[28] = jj_gen;
      ;
    }
    label_19:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        ;
        break;
      default:
        jj_la1[29] = jj_gen;
        break label_19;
      }
      jj_consume_token(SEMICOLON);
      label_20:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[30] = jj_gen;
          break label_20;
        }
        jj_consume_token(S);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENT:
      case EXTENDED_IDENT:
        kfdeclaration();
        break;
      default:
        jj_la1[31] = jj_gen;
        ;
      }
    }
    jj_consume_token(RBRACE);
  }

  final public String toOrFrom() throws ParseException {
    Token t;
    t = jj_consume_token(IDENT);
                        String id = t.image;
                        if ("to".equals(id) || "from".equals(id)) {if (true) return id ;}
                        {if (true) throw new CssException(CssException.SAC_SYNTAX_ERR, "expected 'to' or 'from'", null);}
    throw new Error("Missing return statement in function");
  }

  final public void keyframesSelector() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
      toOrFrom();
      break;
    case PERCENTAGE:
      jj_consume_token(PERCENTAGE);
      break;
    default:
      jj_la1[32] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_21:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[33] = jj_gen;
        break label_21;
      }
      jj_consume_token(S);
    }
  }

  final public void kfdeclaration() throws ParseException {
    property();
    jj_consume_token(COLON);
    label_22:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[34] = jj_gen;
        break label_22;
      }
      jj_consume_token(S);
    }
    expr();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IMPORTANT_SYM:
      prio();
      break;
    default:
      jj_la1[35] = jj_gen;
      ;
    }

  }

// media
//     : MEDIA_SYM S* medium [ ',' S* medium ]* '{' S* ruleset* '}' S*
//     ;
//
  final public void mediaRule() throws ParseException {
    boolean start = false;
    DSacMediaList ml = new DSacMediaList();
    try {
      jj_consume_token(MEDIA_SYM);
      label_23:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[36] = jj_gen;
          break label_23;
        }
        jj_consume_token(S);
      }
      mediaList(ml);
            start = true;
            m_docHandler.startMedia(ml);
      jj_consume_token(LBRACE);
      label_24:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[37] = jj_gen;
          break label_24;
        }
        jj_consume_token(S);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
      case COLON:
      case ASTERISK:
      case LSQUARE:
      case HASH:
      case PAGE_SYM:
      case ATKEYWORD:
      case IDENT:
      case NAMESPACE_IDENT:
      case EMPTY_NAMESPACE_IDENT:
      case STAR_NAMESPACE_IDENT:
      case NAMESPACE_STAR:
        mediaRuleList();
        break;
      default:
        jj_la1[38] = jj_gen;
        ;
      }
      jj_consume_token(RBRACE);
    } finally {
        if (start) {
            m_docHandler.endMedia(ml);
        }
    }
  }

  final public void mediaList(DSacMediaList ml) throws ParseException {
    String s;
    s = medium();
    label_25:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[39] = jj_gen;
        break label_25;
      }
      jj_consume_token(COMMA);
      label_26:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[40] = jj_gen;
          break label_26;
        }
        jj_consume_token(S);
      }
                         ml.add(s);
      s = medium();
    }
      ml.add(s);
  }

  final public void mediaRuleList() throws ParseException {
    label_27:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
      case COLON:
      case ASTERISK:
      case LSQUARE:
      case HASH:
      case IDENT:
      case NAMESPACE_IDENT:
      case EMPTY_NAMESPACE_IDENT:
      case STAR_NAMESPACE_IDENT:
      case NAMESPACE_STAR:
        styleRule();
        break;
      case PAGE_SYM:
        pageRule();
        break;
      case ATKEYWORD:
        unknownRule();
        break;
      default:
        jj_la1[41] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      label_28:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[42] = jj_gen;
          break label_28;
        }
        jj_consume_token(S);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
      case COLON:
      case ASTERISK:
      case LSQUARE:
      case HASH:
      case PAGE_SYM:
      case ATKEYWORD:
      case IDENT:
      case NAMESPACE_IDENT:
      case EMPTY_NAMESPACE_IDENT:
      case STAR_NAMESPACE_IDENT:
      case NAMESPACE_STAR:
        ;
        break;
      default:
        jj_la1[43] = jj_gen;
        break label_27;
      }
    }
  }

  final public void mediaRuleSingle() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOT:
    case COLON:
    case ASTERISK:
    case LSQUARE:
    case HASH:
    case IDENT:
    case NAMESPACE_IDENT:
    case EMPTY_NAMESPACE_IDENT:
    case STAR_NAMESPACE_IDENT:
    case NAMESPACE_STAR:
      styleRule();
      break;
    case PAGE_SYM:
      pageRule();
      break;
    case ATKEYWORD:
      unknownRule();
      break;
    default:
      jj_la1[44] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

// medium
//     : IDENT S*
//     ;
//
  final public String medium() throws ParseException {
    Token t;
    t = jj_consume_token(IDENT);
    label_29:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[45] = jj_gen;
        break label_29;
      }
      jj_consume_token(S);
    }
                           {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

// page
//     : PAGE_SYM S* IDENT? pseudo_page? S*
//     '{' S* declaration [ ';' S* declaration ]* '}' S*
//     ;
//
  final public void pageRule() throws ParseException {
    Token t = null;
    String s = null;
    boolean start = false;
    try {
      jj_consume_token(PAGE_SYM);
      label_30:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[46] = jj_gen;
          break label_30;
        }
        jj_consume_token(S);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COLON:
      case IDENT:
        if (jj_2_1(2)) {
          t = jj_consume_token(IDENT);
          label_31:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case S:
              ;
              break;
            default:
              jj_la1[47] = jj_gen;
              break label_31;
            }
            jj_consume_token(S);
          }
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENT:
            t = jj_consume_token(IDENT);
            s = pseudoPage();
            label_32:
            while (true) {
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case S:
                ;
                break;
              default:
                jj_la1[48] = jj_gen;
                break label_32;
              }
              jj_consume_token(S);
            }
            break;
          case COLON:
            s = pseudoPage();
            label_33:
            while (true) {
              switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
              case S:
                ;
                break;
              default:
                jj_la1[49] = jj_gen;
                break label_33;
              }
              jj_consume_token(S);
            }
            break;
          default:
            jj_la1[50] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        break;
      default:
        jj_la1[51] = jj_gen;
        ;
      }
      jj_consume_token(LBRACE);
      label_34:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[52] = jj_gen;
          break label_34;
        }
        jj_consume_token(S);
      }
            start = true;
            m_docHandler.startPage((t != null) ? unescape(t.image) : null, s);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENT:
      case EXTENDED_IDENT:
        declaration();
        break;
      default:
        jj_la1[53] = jj_gen;
        ;
      }
      label_35:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SEMICOLON:
          ;
          break;
        default:
          jj_la1[54] = jj_gen;
          break label_35;
        }
        jj_consume_token(SEMICOLON);
        label_36:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case S:
            ;
            break;
          default:
            jj_la1[55] = jj_gen;
            break label_36;
          }
          jj_consume_token(S);
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENT:
        case EXTENDED_IDENT:
          declaration();
          break;
        default:
          jj_la1[56] = jj_gen;
          ;
        }
      }
      jj_consume_token(RBRACE);
    } finally {
        if (start) {
            m_docHandler.endPage((t != null) ? unescape(t.image) : null, s);
        }
    }
  }

// pseudoPage
//     : ':' IDENT
//     ;
//
  final public String pseudoPage() throws ParseException {
    Token t;
    jj_consume_token(COLON);
    t = jj_consume_token(IDENT);
                          {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

// font_face
//     : FONT_FACE_SYM S*
//     '{' S* declaration [ ';' S* declaration ]* '}' S*
//     ;
//
  final public void fontFaceRule() throws ParseException {
    boolean start = false;
    try {
      jj_consume_token(FONT_FACE_SYM);
      label_37:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[57] = jj_gen;
          break label_37;
        }
        jj_consume_token(S);
      }
      jj_consume_token(LBRACE);
      label_38:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[58] = jj_gen;
          break label_38;
        }
        jj_consume_token(S);
      }
                            start = true; m_docHandler.startFontFace();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENT:
      case EXTENDED_IDENT:
        declaration();
        break;
      default:
        jj_la1[59] = jj_gen;
        ;
      }
      label_39:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SEMICOLON:
          ;
          break;
        default:
          jj_la1[60] = jj_gen;
          break label_39;
        }
        jj_consume_token(SEMICOLON);
        label_40:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case S:
            ;
            break;
          default:
            jj_la1[61] = jj_gen;
            break label_40;
          }
          jj_consume_token(S);
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENT:
        case EXTENDED_IDENT:
          declaration();
          break;
        default:
          jj_la1[62] = jj_gen;
          ;
        }
      }
      jj_consume_token(RBRACE);
    } finally {
        if (start) {
            m_docHandler.endFontFace();
        }
    }
  }

// operator
//     : '/' S* | ',' S* |
//     ;
//
  final public ILexicalUnit operator(ILexicalUnit prev) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SLASH:
      jj_consume_token(SLASH);
      label_41:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[63] = jj_gen;
          break label_41;
        }
        jj_consume_token(S);
      }
                           {if (true) return new DLexicalUnit(prev, ILexicalUnit.SAC_OPERATOR_SLASH);}
      break;
    case COMMA:
      jj_consume_token(COMMA);
      label_42:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[64] = jj_gen;
          break label_42;
        }
        jj_consume_token(S);
      }
                         {if (true) return new DLexicalUnit(prev, ILexicalUnit.SAC_OPERATOR_COMMA);}
      break;
    default:
      jj_la1[65] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// combinator
//     : '+' S* | '>' S* |
//     ;
//
  final public char combinator() throws ParseException {
    char c = ' ';
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
      jj_consume_token(PLUS);
               c='+';
      label_43:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[66] = jj_gen;
          break label_43;
        }
        jj_consume_token(S);
      }
      break;
    case GT:
      jj_consume_token(GT);
             c='>';
      label_44:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[67] = jj_gen;
          break label_44;
        }
        jj_consume_token(S);
      }
      break;
    case TILDE:
      jj_consume_token(TILDE);
                c='~';
      label_45:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[68] = jj_gen;
          break label_45;
        }
        jj_consume_token(S);
      }
      break;
    case S:
      jj_consume_token(S);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case GT:
      case TILDE:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
          jj_consume_token(PLUS);
                       c='+';
          break;
        case GT:
          jj_consume_token(GT);
                                         c='>';
          break;
        case TILDE:
          jj_consume_token(TILDE);
                                                              c='~';
          break;
        default:
          jj_la1[69] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        label_46:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case S:
            ;
            break;
          default:
            jj_la1[70] = jj_gen;
            break label_46;
          }
          jj_consume_token(S);
        }
        break;
      default:
        jj_la1[71] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[72] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

// unary_operator
//     : '-' | '+'
//     ;
//
  final public char unaryOperator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      jj_consume_token(MINUS);
                {if (true) return '-';}
      break;
    case PLUS:
      jj_consume_token(PLUS);
                                         {if (true) return '+';}
      break;
    default:
      jj_la1[73] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// property
//     : IDENT S*
//     ;
//
  final public String property() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
      t = jj_consume_token(IDENT);
      label_47:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[74] = jj_gen;
          break label_47;
        }
        jj_consume_token(S);
      }
      {if (true) return unescape(t.image);}
      break;
    case EXTENDED_IDENT:
      t = jj_consume_token(EXTENDED_IDENT);
      label_48:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[75] = jj_gen;
          break label_48;
        }
        jj_consume_token(S);
      }
      {if (true) return unescape(t.image);}
      break;
    default:
      jj_la1[76] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// ruleset
//     : selector [ ',' S* selector ]*
//     '{' S* declaration [ ';' S* declaration ]* '}' S*
//     ;
//
  final public void styleRule() throws ParseException {
    ISelectorList selList = null;
    boolean start = false;
    try {
      selList = selectorList();
      jj_consume_token(LBRACE);
      label_49:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[77] = jj_gen;
          break label_49;
        }
        jj_consume_token(S);
      }
            start = true;
            m_docHandler.startSelector(selList);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENT:
      case EXTENDED_IDENT:
        declaration();
        break;
      default:
        jj_la1[78] = jj_gen;
        ;
      }
      label_50:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SEMICOLON:
          ;
          break;
        default:
          jj_la1[79] = jj_gen;
          break label_50;
        }
        jj_consume_token(SEMICOLON);
        label_51:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case S:
            ;
            break;
          default:
            jj_la1[80] = jj_gen;
            break label_51;
          }
          jj_consume_token(S);
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENT:
        case EXTENDED_IDENT:
          declaration();
          break;
        default:
          jj_la1[81] = jj_gen;
          ;
        }
      }
      jj_consume_token(RBRACE);
    } catch (ParseException e) {
        m_errorMessage.append("Exception in styleRule: ").append(e.getMessage()).append("\n");
        error_skipblock();
    } finally {
        if (start) {
            m_docHandler.endSelector(selList);
        }
    }
  }

  final public ISelectorList selectorList() throws ParseException {
    DSelectorList selList = new DSelectorList();
    ISelector sel;
    try {
      sel = selector();
      label_52:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[82] = jj_gen;
          break label_52;
        }
        jj_consume_token(COMMA);
        label_53:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case S:
            ;
            break;
          default:
            jj_la1[83] = jj_gen;
            break label_53;
          }
          jj_consume_token(S);
        }
                             selList.add(sel);
        sel = selector();
      }
            selList.add(sel);
            {if (true) return selList;}
    } catch (ParseException e) {
        m_errorMessage.append("Exception in selectorList: ").append(e.getMessage()).append("\n");
    }
    throw new Error("Missing return statement in function");
  }

// selector
//     : simple_selector [ combinator simple_selector ]*
//     ;
//
  final public ISelector selector() throws ParseException {
    ISelector sel;
    char comb;
    try {
      sel = simpleSelector(null, ' ');
      label_54:
      while (true) {
        if (jj_2_2(2)) {
          ;
        } else {
          break label_54;
        }
        comb = combinator();
        sel = simpleSelector(sel, comb);
      }
      label_55:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[84] = jj_gen;
          break label_55;
        }
        jj_consume_token(S);
      }
            {if (true) return sel;}
    } catch (ParseException e) {
        m_errorMessage.append("Exception in selectorList: ").append(e.getMessage()).append("\n");
        skipSelector();
    }
    throw new Error("Missing return statement in function");
  }

// simple_selector
//     : element_name? [ HASH | class | attrib | pseudo ]* S*
//     ;
//
  final public ISelector simpleSelector(ISelector sel, char comb) throws ParseException {
    ISimpleSelector simpleSel = null;
    ICondition c = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASTERISK:
    case IDENT:
    case NAMESPACE_IDENT:
    case EMPTY_NAMESPACE_IDENT:
    case STAR_NAMESPACE_IDENT:
    case NAMESPACE_STAR:
      simpleSel = elementName();
      label_56:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DOT:
        case COLON:
        case LSQUARE:
        case HASH:
          ;
          break;
        default:
          jj_la1[85] = jj_gen;
          break label_56;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case HASH:
          c = hash(c);
          break;
        case DOT:
          c = _class(c);
          break;
        case LSQUARE:
          c = attrib(c);
          break;
        case COLON:
          c = pseudo(c);
          break;
        default:
          jj_la1[86] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      break;
    case DOT:
    case COLON:
    case LSQUARE:
    case HASH:
            simpleSel = m_selectorFactory.createElementSelector(null, null);
      label_57:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case HASH:
          c = hash(c);
          break;
        case DOT:
          c = _class(c);
          break;
        case LSQUARE:
          c = attrib(c);
          break;
        case COLON:
          c = pseudo(c);
          break;
        default:
          jj_la1[87] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DOT:
        case COLON:
        case LSQUARE:
        case HASH:
          ;
          break;
        default:
          jj_la1[88] = jj_gen;
          break label_57;
        }
      }
      break;
    default:
      jj_la1[89] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
        if (c != null) {
            simpleSel = m_selectorFactory.createConditionalSelector(simpleSel, c);
        }

        if (sel != null) {
            switch (comb) {
            case ' ':
                sel = m_selectorFactory.createDescendantSelector(sel, simpleSel);
                break;
            case '+':
                sel = m_selectorFactory.createDirectAdjacentSelector(sel.getSelectorType(), sel, simpleSel);
                break;
            case '>':
                sel = m_selectorFactory.createChildSelector(sel, simpleSel);
                break;
            case '~':
                sel = m_selectorFactory.createGeneralSiblingSelector(sel.getSelectorType(), sel, simpleSel);
                break;
            }
        } else {
            sel = simpleSel;
        }

        {if (true) return sel;}
    throw new Error("Missing return statement in function");
  }

// class
//     : '.' IDENT
//     ;
//
  final public ICondition _class(ICondition pred) throws ParseException {
    Token t;
    jj_consume_token(DOT);
    t = jj_consume_token(IDENT);
        ICondition c = m_conditionFactory.createClassCondition(null, t.image);
        {if (true) return (pred == null) ? c : m_conditionFactory.createAndCondition(pred, c);}
    throw new Error("Missing return statement in function");
  }

// element_name
//     : IDENT | '*'
//     ;
//
  final public ISimpleSelector elementName() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
      t = jj_consume_token(IDENT);
          {if (true) return m_selectorFactory.createElementSelector(null, unescape(t.image));}
      break;
    case ASTERISK:
      t = jj_consume_token(ASTERISK);
          {if (true) return m_selectorFactory.createElementSelector(null, null);}
      break;
    case NAMESPACE_IDENT:
      t = jj_consume_token(NAMESPACE_IDENT);
          {if (true) return m_selectorFactory.createElementSelector(null, unescape(t.image));}
      break;
    case NAMESPACE_STAR:
      t = jj_consume_token(NAMESPACE_STAR);
          {if (true) return m_selectorFactory.createElementSelector(null, unescape(t.image));}
      break;
    case EMPTY_NAMESPACE_IDENT:
      t = jj_consume_token(EMPTY_NAMESPACE_IDENT);
          {if (true) return m_selectorFactory.createElementSelector(null, unescape(t.image));}
      break;
    case STAR_NAMESPACE_IDENT:
      t = jj_consume_token(STAR_NAMESPACE_IDENT);
          {if (true) return m_selectorFactory.createElementSelector(null, unescape(t.image));}
      break;
    default:
      jj_la1[90] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Token attribIdentifier() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
      t = jj_consume_token(IDENT);
      {if (true) return t;}
      break;
    case EXTENDED_IDENT:
      t = jj_consume_token(EXTENDED_IDENT);
      {if (true) return t;}
      break;
    default:
      jj_la1[91] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// attrib
//     : '[' S* IDENT S* [ [ EQUALS | INCLUDES | DASHMATCH | STARTS_WITH | ENDS_WITH | CONTAINS_AT_LEAST_ONE ] S*
//     [ IDENT | STRING ] S* ]? ']'
//     ;
//
  final public ICondition attrib(ICondition pred) throws ParseException {
    Token t;
    String name = null;
    String value = null;
    int type = 0;
    jj_consume_token(LSQUARE);
    label_58:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[92] = jj_gen;
        break label_58;
      }
      jj_consume_token(S);
    }
    t = attribIdentifier();
                             name = unescape(t.image);
    label_59:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[93] = jj_gen;
        break label_59;
      }
      jj_consume_token(S);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUALS:
    case INCLUDES:
    case DASHMATCH:
    case STARTS_WITH:
    case ENDS_WITH:
    case CONTAINS_AT_LEAST_ONE:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQUALS:
        jj_consume_token(EQUALS);
                       type = 1;
        break;
      case INCLUDES:
        jj_consume_token(INCLUDES);
                         type = 2;
        break;
      case DASHMATCH:
        jj_consume_token(DASHMATCH);
                          type = 3;
        break;
      case STARTS_WITH:
        jj_consume_token(STARTS_WITH);
                            type = 4;
        break;
      case ENDS_WITH:
        jj_consume_token(ENDS_WITH);
                          type = 5;
        break;
      case CONTAINS_AT_LEAST_ONE:
        jj_consume_token(CONTAINS_AT_LEAST_ONE);
                                      type = 6;
        break;
      default:
        jj_la1[94] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      label_60:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[95] = jj_gen;
          break label_60;
        }
        jj_consume_token(S);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENT:
        t = jj_consume_token(IDENT);
                          value = t.image;
        break;
      case STRING:
        t = jj_consume_token(STRING);
                           value = unescape(t.image);
        break;
      default:
        jj_la1[96] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      label_61:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[97] = jj_gen;
          break label_61;
        }
        jj_consume_token(S);
      }
      break;
    default:
      jj_la1[98] = jj_gen;
      ;
    }
    jj_consume_token(RSQUARE);
        ICondition c = null;
        switch (type) {
        case 0: // E[attr]
            c = m_conditionFactory.createAttributeCondition(name, null, false, null);
            break;
        case 1: // E[attr="foo"]
            c = m_conditionFactory.createAttributeCondition(name, null, false, value);
            break;
        case 2: // E[attr ~= "foo"] {color:red}
            c = m_conditionFactory.createOneOfAttributeCondition(name, null, false, value);
            break;
        case 3: // E[foo |= "bar"]
            c = m_conditionFactory.createIsOrStartsWithAttributeCondition(name, null, false, value);
            break;
        case 4: // E[attr ^= "foo"] {color:red}
            c = m_conditionFactory.createStartsWithAttributeCondition(name, null, false, value);
            break;
        case 5: // E[attr $= "foo"] {color:red}
            c = m_conditionFactory.createEndsWithAttributeCondition(name, null, false, value);
            break;
        case 6: // E[attr *= "foo"] {color:red}
            c = m_conditionFactory.createContainsAtLeastOneAttributeCondition(name, null, false, value);
            break;
        }
        {if (true) return (pred == null)
                ? c
                : m_conditionFactory.createAndCondition(pred, c);}
    throw new Error("Missing return statement in function");
  }

// simpleArg
//     : id | integer | "*"
//     ;
//
  final public Token simpleArg() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
      t = jj_consume_token(IDENT);
                  {if (true) return t;}
      break;
    case NUMBER:
      t = jj_consume_token(NUMBER);
                       {if (true) return t;}
      break;
    case ASTERISK:
      t = jj_consume_token(ASTERISK);
                         {if (true) return t;}
      break;
    default:
      jj_la1[99] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Token pseudoIdentifier() throws ParseException {
        Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
      t = jj_consume_token(IDENT);
                  {if (true) return t;}
      break;
    case EXTENDED_IDENT:
      t = jj_consume_token(EXTENDED_IDENT);
                               {if (true) return t;}
      break;
    default:
      jj_la1[100] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Token extendedIdentFunction() throws ParseException {
        Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FUNCTION:
      t = jj_consume_token(FUNCTION);
      {if (true) return t;}
      break;
    case EXTENDED_IDENT_FUNCTION:
      t = jj_consume_token(EXTENDED_IDENT_FUNCTION);
      {if (true) return t;}
      break;
    default:
      jj_la1[101] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// pseudo
//     : ':' [ IDENT | FUNCTION S* IDENT S* ')' ]
//     ;
//
  final public ICondition pseudo(ICondition pred) throws ParseException {
    ICondition c = null;
    Token t;
    String function = null;
    String arg = null;
    ISimpleSelector simpleSel;
    jj_consume_token(COLON);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COLON:
      jj_consume_token(COLON);
      break;
    default:
      jj_la1[102] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
    case EXTENDED_IDENT:
      t = pseudoIdentifier();
            // There appears to be an issue here regarding "first-letter" & "first-line"
            String s = unescape(t.image);
            c = m_conditionFactory.createPseudoClassCondition(null, s);
            {if (true) return (pred == null)
                ? c
                : m_conditionFactory.createAndCondition(pred, c);}
      break;
    case FUNCTION:
    case EXTENDED_IDENT_FUNCTION:
      t = extendedIdentFunction();
              function = unescape(t.image);
      t = simpleArg();
                              arg = unescape(t.image);
      label_62:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[103] = jj_gen;
          break label_62;
        }
        jj_consume_token(S);
      }
      jj_consume_token(RROUND);
                /* Handle the following:
            	E:nth-child(1)
            	E:nth-child(odd)     // not implemented yet
            	E:nth-child(even)	 // not implemented yet
            	E:nth-child(2n + 1)	 // not implemented yet
            	E:nth-last-child(2)
            	E:nth-of-type(id)
            	E:nth-last-of-type(4)
            	E:not(id)
            	E:lang(fr)
            	*/
                String func = function.substring(0, function.length() - 1) ;
                c = m_conditionFactory.createPseudoFunction(func, unescape(arg));
                if (c == null) {
                    {if (true) throw new CssParseException(
                        "Invalid pseudo function name " + function, getLocator());}
                }
                {if (true) return (pred == null)
                        ? c
                    : m_conditionFactory.createAndCondition(pred, c);}
      break;
    default:
      jj_la1[104] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ICondition hash(ICondition pred) throws ParseException {
    Token t;
    t = jj_consume_token(HASH);
        ICondition c = m_conditionFactory.createIdCondition(t.image.substring(1));
        {if (true) return (pred == null) ? c : m_conditionFactory.createAndCondition(pred, c);}
    throw new Error("Missing return statement in function");
  }

  final public void styleDeclaration() throws ParseException {
    jj_consume_token(LBRACE);
    label_63:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[105] = jj_gen;
        break label_63;
      }
      jj_consume_token(S);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENT:
    case EXTENDED_IDENT:
      declaration();
      break;
    default:
      jj_la1[106] = jj_gen;
      ;
    }
    label_64:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMICOLON:
        ;
        break;
      default:
        jj_la1[107] = jj_gen;
        break label_64;
      }
      jj_consume_token(SEMICOLON);
      label_65:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[108] = jj_gen;
          break label_65;
        }
        jj_consume_token(S);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENT:
      case EXTENDED_IDENT:
        declaration();
        break;
      default:
        jj_la1[109] = jj_gen;
        ;
      }
    }
    jj_consume_token(RBRACE);
  }

// declaration
//     : property ':' S* expr prio?
//     |
//     ;
//
  final public void declaration() throws ParseException {
    String p;
    ILexicalUnit e;  // used to be of type CSSValue
    boolean priority = false;
    try {
      p = property();
      jj_consume_token(COLON);
      label_66:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case S:
          ;
          break;
        default:
          jj_la1[110] = jj_gen;
          break label_66;
        }
        jj_consume_token(S);
      }
      e = expr();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPORTANT_SYM:
        priority = prio();
        break;
      default:
        jj_la1[111] = jj_gen;
        ;
      }
            m_docHandler.property(p, e, priority);
    } catch (ParseException ex) {
        m_errorMessage.append("Exception in declaration: ").append(ex.getMessage()).append("\n");
        error_skipdecl();
    }
  }

// prio
//     : IMPORTANT_SYM S*
//     ;
//
  final public boolean prio() throws ParseException {
    jj_consume_token(IMPORTANT_SYM);
    label_67:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[112] = jj_gen;
        break label_67;
      }
      jj_consume_token(S);
    }
      {if (true) return true;}
    throw new Error("Missing return statement in function");
  }

// expr
//     : term [ operator term ]*
//     ;
//
// TODO: Deal with the operator
//
  final public ILexicalUnit expr() throws ParseException {
    ILexicalUnit head;
    ILexicalUnit body;
    head = term(null);
                        body = head;
    label_68:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
      case SLASH:
      case PLUS:
      case MINUS:
      case HASH:
      case STRING:
      case URI:
      case INHERIT:
      case EMS:
      case EXS:
      case LENGTH_PX:
      case LENGTH_CM:
      case LENGTH_MM:
      case LENGTH_IN:
      case LENGTH_PT:
      case LENGTH_PC:
      case ANGLE_DEG:
      case ANGLE_RAD:
      case ANGLE_GRAD:
      case TIME_MS:
      case TIME_S:
      case FREQ_HZ:
      case FREQ_KHZ:
      case DIMEN:
      case PERCENTAGE:
      case NUMBER:
      case RGB:
      case RGBA:
      case HSL:
      case HSLA:
      case IDENT:
      case EXTENDED_IDENT:
      case FUNCTION:
      case EXTENDED_IDENT_FUNCTION:
      case UNICODERANGE:
        ;
        break;
      default:
        jj_la1[113] = jj_gen;
        break label_68;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
      case SLASH:
        body = operator(body);
        break;
      default:
        jj_la1[114] = jj_gen;
        ;
      }
      body = term(body);
    }
      {if (true) return head;}
    throw new Error("Missing return statement in function");
  }

// term
//     : unary_operator?
//     [ NUMBER S* | PERCENTAGE S* | LENGTH S* | EMS S* | EXS S* | ANGLE S* | TIME S* | FREQ S* | function ]
//     | STRING S* | IDENT S* | URI S* | UNICODERANGE S* | RGB S* | RGBA S* | HSL S* | HSLA S* | hexcolor S*
//     ;
//
  final public ILexicalUnit term(ILexicalUnit prev) throws ParseException {
    Token t;
    char op = ' ';
    ILexicalUnit value = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
    case MINUS:
      op = unaryOperator();
      break;
    default:
      jj_la1[115] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
      t = jj_consume_token(NUMBER);
                                value = DLexicalUnit.createNumber(prev, value(op, t.image));
      break;
    case PERCENTAGE:
      t = jj_consume_token(PERCENTAGE);
                                value = DLexicalUnit.createPercentage(prev, value(op, t.image));
      break;
    case LENGTH_PX:
      t = jj_consume_token(LENGTH_PX);
                                value = DLexicalUnit.createPixel(prev, value(op, t.image));
      break;
    case LENGTH_CM:
      t = jj_consume_token(LENGTH_CM);
                                value = DLexicalUnit.createCentimeter(prev, value(op, t.image));
      break;
    case LENGTH_MM:
      t = jj_consume_token(LENGTH_MM);
                                value = DLexicalUnit.createMillimeter(prev, value(op, t.image));
      break;
    case LENGTH_IN:
      t = jj_consume_token(LENGTH_IN);
                                value = DLexicalUnit.createInch(prev, value(op, t.image));
      break;
    case LENGTH_PT:
      t = jj_consume_token(LENGTH_PT);
                                value = DLexicalUnit.createPoint(prev, value(op, t.image));
      break;
    case LENGTH_PC:
      t = jj_consume_token(LENGTH_PC);
                                value = DLexicalUnit.createPica(prev, value(op, t.image));
      break;
    case EMS:
      t = jj_consume_token(EMS);
                              value = DLexicalUnit.createEm(prev, value(op, t.image));
      break;
    case EXS:
      t = jj_consume_token(EXS);
                              value = DLexicalUnit.createEx(prev, value(op, t.image));
      break;
    case ANGLE_DEG:
      t = jj_consume_token(ANGLE_DEG);
                                value = DLexicalUnit.createDegree(prev, value(op, t.image));
      break;
    case ANGLE_RAD:
      t = jj_consume_token(ANGLE_RAD);
                                value = DLexicalUnit.createRadian(prev, value(op, t.image));
      break;
    case ANGLE_GRAD:
      t = jj_consume_token(ANGLE_GRAD);
                                value = DLexicalUnit.createGradian(prev, value(op, t.image));
      break;
    case TIME_MS:
      t = jj_consume_token(TIME_MS);
                              value = DLexicalUnit.createMillisecond(prev, value(op, t.image));
      break;
    case TIME_S:
      t = jj_consume_token(TIME_S);
                                value = DLexicalUnit.createSecond(prev, value(op, t.image));
      break;
    case FREQ_HZ:
      t = jj_consume_token(FREQ_HZ);
                              value = DLexicalUnit.createHertz(prev, value(op, t.image));
      break;
    case FREQ_KHZ:
      t = jj_consume_token(FREQ_KHZ);
                              value = DLexicalUnit.createKiloHertz(prev, value(op, t.image));
      break;
    case STRING:
      t = jj_consume_token(STRING);
                                  value = new DLexicalUnit(prev, ILexicalUnit.SAC_STRING_VALUE, t.image);
      break;
    case IDENT:
      t = jj_consume_token(IDENT);
                                  value = new DLexicalUnit(prev, ILexicalUnit.SAC_IDENT, t.image);
      break;
    case EXTENDED_IDENT:
      t = jj_consume_token(EXTENDED_IDENT);
                                  value = new DLexicalUnit(prev, ILexicalUnit.SAC_IDENT, t.image);
      break;
    case URI:
      t = jj_consume_token(URI);
                                  value = new DLexicalUnit(prev, ILexicalUnit.SAC_URI, t.image);
      break;
    case UNICODERANGE:
      t = jj_consume_token(UNICODERANGE);
                                  value = new DLexicalUnit(prev, ILexicalUnit.SAC_UNICODERANGE, t.image);
      break;
    case RGB:
      value = rgb(prev);
      break;
    case RGBA:
      value = rgba(prev);
      break;
    case HSL:
      value = hsl(prev);
      break;
    case HSLA:
      value = hsla(prev);
      break;
    case HASH:
      value = hexcolor(prev);
      break;
    case FUNCTION:
    case EXTENDED_IDENT_FUNCTION:
      value = function(prev);
      break;
    case DIMEN:
      t = jj_consume_token(DIMEN);
            int n = getLastNumPos(t.image);
            value = DLexicalUnit.createDimension(
                prev,
                value(op, t.image.substring(0, n+1)),
                t.image.substring(n+1));
      break;
    case INHERIT:
      t = jj_consume_token(INHERIT);
                value = new DLexicalUnit(prev, ILexicalUnit.SAC_INHERIT, t.image);
      break;
    default:
      jj_la1[116] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_69:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[117] = jj_gen;
        break label_69;
      }
      jj_consume_token(S);
    }
      {if (true) return value;}
    throw new Error("Missing return statement in function");
  }

// function
//     : FUNCTION S* expr ')' S*
//     ;
//
  final public ILexicalUnit function(ILexicalUnit prev) throws ParseException {
    Token t;
    ILexicalUnit params;
    //???
        t = extendedIdentFunction();
    label_70:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[118] = jj_gen;
        break label_70;
      }
      jj_consume_token(S);
    }
    params = expr();
    jj_consume_token(RROUND);
        String v = t.image.toLowerCase() ;
        if (t.equals("counter(")) {
             {if (true) return DLexicalUnit.createCounter(prev, params);}
        } else if (t.equals("counters(")) {
             {if (true) return DLexicalUnit.createCounters(prev, params);}
        } else if (t.equals("attr(")) {
             {if (true) return DLexicalUnit.createAttr(prev, params);}
        } else if (t.equals("rect(")) {
             {if (true) return DLexicalUnit.createRect(prev, params);}
        }
        {if (true) return DLexicalUnit.createFunction(
            prev,
            t.image.substring(0, t.image.length() - 1),
            params);}
    throw new Error("Missing return statement in function");
  }

// rgb
//     : RGB S* expr ')' S*
//     ;
//
  final public ILexicalUnit rgb(ILexicalUnit prev) throws ParseException {
    ILexicalUnit params;
    jj_consume_token(RGB);
    label_71:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[119] = jj_gen;
        break label_71;
      }
      jj_consume_token(S);
    }
    params = expr();
    jj_consume_token(RROUND);
        {if (true) return DLexicalUnit.createRgbColor(prev, params);}
    throw new Error("Missing return statement in function");
  }

  final public ILexicalUnit rgba(ILexicalUnit prev) throws ParseException {
    ILexicalUnit params;
    jj_consume_token(RGBA);
    label_72:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[120] = jj_gen;
        break label_72;
      }
      jj_consume_token(S);
    }
    params = expr();
    jj_consume_token(RROUND);
        {if (true) return DLexicalUnit.createRgbaColor(prev, params);}
    throw new Error("Missing return statement in function");
  }

  final public ILexicalUnit hsl(ILexicalUnit prev) throws ParseException {
    ILexicalUnit params;
    jj_consume_token(HSL);
    label_73:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[121] = jj_gen;
        break label_73;
      }
      jj_consume_token(S);
    }
    params = expr();
    jj_consume_token(RROUND);
        {if (true) return DLexicalUnit.createHslColor(prev, params);}
    throw new Error("Missing return statement in function");
  }

  final public ILexicalUnit hsla(ILexicalUnit prev) throws ParseException {
    ILexicalUnit params;
    jj_consume_token(HSLA);
    label_74:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case S:
        ;
        break;
      default:
        jj_la1[122] = jj_gen;
        break label_74;
      }
      jj_consume_token(S);
    }
    params = expr();
    jj_consume_token(RROUND);
        {if (true) return DLexicalUnit.createHslaColor(prev, params);}
    throw new Error("Missing return statement in function");
  }

// hexcolor
//     : HASH S*
//     ;
//
  final public ILexicalUnit hexcolor(ILexicalUnit prev) throws ParseException {
    Token t;
    t = jj_consume_token(HASH);
        int i = 1;
        int r = 0;
        int g = 0;
        int b = 0;
        int len = t.image.length() - 1;  // don't include the #

        if (len == 3) {
            r = Integer.parseInt(t.image.substring(i + 0, i + 1), 16);
            g = Integer.parseInt(t.image.substring(i + 1, i + 2), 16);
            b = Integer.parseInt(t.image.substring(i + 2, i + 3), 16);
            r = (r << 4) | r;
            g = (g << 4) | g;
            b = (b << 4) | b;
        } else if (len == 6) {
            r = Integer.parseInt(t.image.substring(i + 0, i + 2), 16);
            g = Integer.parseInt(t.image.substring(i + 2, i + 4), 16);
            b = Integer.parseInt(t.image.substring(i + 4, i + 6), 16);
        } else {
            m_errorMessage.append("Invalid color: ").append(t.image);
        }

        // turn into an "rgb()"
        ILexicalUnit lr = DLexicalUnit.createNumber(null, r);
        ILexicalUnit lc1 = DLexicalUnit.createComma(lr);
        ILexicalUnit lg = DLexicalUnit.createNumber(lc1, g);
        ILexicalUnit lc2 = DLexicalUnit.createComma(lg);
        DLexicalUnit.createNumber(lc2, b);

        {if (true) return DLexicalUnit.createRgbColor(prev, lr);}
    throw new Error("Missing return statement in function");
  }

  float value(char op, String s) throws ParseException {
    return ((op == '-') ? -1 : 1) * Float.parseFloat(s);
  }

  int getLastNumPos(String s) throws ParseException {
    int i;
    for (i = 0; i < s.length(); i++) {
        if (Character.isLetter(s.charAt(i))) {
            break;
        }
    }
    return i - 1;
  }

  String unescape(String s) throws ParseException {
    int len = s.length();
    StringBuffer buf = new StringBuffer(len);
    int index = 0;

    while (index < len) {
        char c = s.charAt(index);
        if (c == '\\') {
            if (++index < len) {
                c = s.charAt(index);
                switch (c) {
                case '0': case '1': case '2': case '3': case '4':
                case '5': case '6': case '7': case '8': case '9':
                case 'a': case 'b': case 'c': case 'd': case 'e': case 'f':
                case 'A': case 'B': case 'C': case 'D': case 'E': case 'F':
                    int numValue = Character.digit(c, 16);
                    int count = 0;
                    int p = 16;

                    while (index + 1 < len && count < 6) {
                        c = s.charAt(index+1);

                        if (Character.digit(c, 16) != -1) {
                            numValue = (numValue * 16) + Character.digit(c, 16);
                            p *= 16;
                            index++;
                        } else {
                            if (c == ' ') {
                                // skip the latest white space
                                index++;
                            }
                            break;
                        }
                    }
                    buf.append((char) numValue);
                    break;
                    case '\n':
                    case '\f':
                    break;
                    case '\r':
                    if (index + 1 < len) {
                        if (s.charAt(index + 1) == '\n') {
                            index ++;
                        }
                    }
                    break;
                default:
                    buf.append(c);
                }
            } else {
                throw new CssParseException("invalid string " + s, getLocator());
            }
        } else {
            buf.append(c);
        }
        index++;
    }

    return buf.toString();
  }

  void skipSelector() throws ParseException {
    Token t = getToken(1);
    while (t.kind != COMMA && t.kind != SEMICOLON && t.kind != LBRACE && t.kind != EOF ) {
        getNextToken();
        t = getToken(1);
    }
  }

  String skip() throws ParseException {
    StringBuffer sb = new StringBuffer();
    int nesting = 0;
    Token t = getToken(0);
    if (t.image != null) {
    sb.append(t.image);
    }
    do {
    t = getNextToken();
    if (t.kind == EOF)
        break;
    sb.append(t.image);
    if (t.kind == LBRACE)
        nesting++;
    else if (t.kind == RBRACE)
        nesting--;
    else if (t.kind == SEMICOLON && nesting <= 0)
        break;
    }
    while ((t.kind != RBRACE) || (nesting > 0));

    return sb.toString();
  }

  void error_skipblock() throws ParseException {
    if (!m_quiet) {
        ParseException e = generateParseException();
        System.err.println( "** error_skipblock **\n" + e.toString() );
    }

    Token t;
    int nesting = 0;
    do {
    t = getNextToken();
    if( t.kind == LBRACE )
        nesting++;
    else if( t.kind == RBRACE )
        nesting--;
    else if( t.kind == EOF )
        break;
    }
    while ((t.kind != RBRACE) || (nesting > 0));
  }

  void error_skipdecl() throws ParseException {
    if (!m_quiet) {
        ParseException e = generateParseException();
        System.err.println("** error_skipdecl **\n" + e.toString());
    }

    Token t = getToken(1);
    while (t.kind != SEMICOLON && t.kind != RBRACE && t.kind != EOF ) {
        getNextToken();
        t = getToken(1);
    }
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_1();
    jj_save(0, xla);
    return retval;
  }

  final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_2();
    jj_save(1, xla);
    return retval;
  }

  final private boolean jj_3R_86() {
    if (jj_scan_token(S)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_104() {
    if (jj_scan_token(DOT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_84() {
    if (jj_scan_token(S)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_85() {
    if (jj_scan_token(S)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_82() {
    if (jj_3R_88()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_77() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_82()) {
    jj_scanpos = xsp;
    if (jj_3R_83()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_90() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_87() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_90()) {
    jj_scanpos = xsp;
    if (jj_3R_91()) {
    jj_scanpos = xsp;
    if (jj_3R_92()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_75() {
    if (jj_scan_token(S)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_81() {
    if (jj_scan_token(S)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_87()) jj_scanpos = xsp;
    else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_92() {
    if (jj_scan_token(TILDE)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_80() {
    if (jj_scan_token(TILDE)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_86()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  final private boolean jj_3R_79() {
    if (jj_scan_token(GT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_85()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  final private boolean jj_3_2() {
    if (jj_3R_76()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_77()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_98() {
    if (jj_scan_token(STAR_NAMESPACE_IDENT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_78() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_84()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  final private boolean jj_3R_97() {
    if (jj_scan_token(EMPTY_NAMESPACE_IDENT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_76() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_78()) {
    jj_scanpos = xsp;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3R_80()) {
    jj_scanpos = xsp;
    if (jj_3R_81()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_96() {
    if (jj_scan_token(NAMESPACE_STAR)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_95() {
    if (jj_scan_token(NAMESPACE_IDENT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_94() {
    if (jj_scan_token(ASTERISK)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_106() {
    if (jj_scan_token(COLON)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_102() {
    if (jj_3R_106()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_101() {
    if (jj_3R_105()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_100() {
    if (jj_3R_104()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_93() {
    if (jj_scan_token(IDENT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_88() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_93()) {
    jj_scanpos = xsp;
    if (jj_3R_94()) {
    jj_scanpos = xsp;
    if (jj_3R_95()) {
    jj_scanpos = xsp;
    if (jj_3R_96()) {
    jj_scanpos = xsp;
    if (jj_3R_97()) {
    jj_scanpos = xsp;
    if (jj_3R_98()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_99() {
    if (jj_3R_103()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_89() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_99()) {
    jj_scanpos = xsp;
    if (jj_3R_100()) {
    jj_scanpos = xsp;
    if (jj_3R_101()) {
    jj_scanpos = xsp;
    if (jj_3R_102()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_91() {
    if (jj_scan_token(GT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_103() {
    if (jj_scan_token(HASH)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3R_83() {
    Token xsp;
    if (jj_3R_89()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_89()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  final private boolean jj_3R_105() {
    if (jj_scan_token(LSQUARE)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  final private boolean jj_3_1() {
    if (jj_scan_token(IDENT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_75()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  public SacParserTokenManager token_source;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  // private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[123];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_0();
      jj_la1_1();
      jj_la1_2();
      jj_la1_3();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x0,0x18000002,0x18000002,0x0,0x18000002,0x18000002,0x0,0x440d00,0x440d00,0x18000002,0x18000002,0x440d00,0x2,0x2,0x2,0x0,0x2,0x2,0x4800000,0x2,0x0,0x800000,0x2,0x2,0x2,0x0,0x2,0x2,0x0,0x200,0x2,0x0,0x0,0x2,0x2,0x0,0x2,0x2,0x440d00,0x80,0x2,0x440d00,0x2,0x440d00,0x440d00,0x2,0x2,0x2,0x2,0x2,0x400,0x400,0x2,0x0,0x200,0x2,0x0,0x2,0x2,0x0,0x200,0x2,0x0,0x2,0x2,0x1080,0x2,0x2,0x2,0x122000,0x2,0x122000,0x122002,0x6000,0x2,0x2,0x0,0x2,0x0,0x200,0x2,0x0,0x80,0x2,0x2,0x440500,0x440500,0x440500,0x440500,0x440d00,0x800,0x0,0x2,0x2,0xe0010000,0x2,0x800000,0x2,0xe0010000,0x800,0x0,0x0,0x400,0x2,0x0,0x2,0x0,0x200,0x2,0x0,0x2,0x0,0x2,0x4c07080,0x1080,0x6000,0x4c00000,0x2,0x2,0x2,0x2,0x2,0x2,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x80,0x0,0x0,0x4,0x0,0x0,0x100,0x278,0x278,0x0,0x0,0x3fc,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10000000,0x0,0x0,0x0,0x0,0x0,0x0,0x10000000,0x0,0x0,0x400,0x0,0x0,0x208,0x0,0x0,0x208,0x0,0x208,0x208,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3,0x0,0x0,0x0,0x3,0x20000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x400,0x0,0xfffff800,0x0,0x0,0xfffff800,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1e4,0x1e4,0x0,0x0,0x1e4,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x0,0x4,0x4,0x0,0x0,0x0,0x4,0x0,0x0,0x14,0x0,0x0,0x14,0x4,0x0,0x0,0x0,0x0,0x0,0x1e4,0x0,0x0,0x1e4,0x0,0x1e4,0x1e4,0x0,0x0,0x0,0x0,0x0,0x4,0x4,0x0,0x14,0x0,0x0,0x14,0x0,0x0,0x14,0x0,0x0,0x14,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x14,0x0,0x14,0x0,0x0,0x14,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1e4,0x1e4,0x14,0x0,0x0,0x0,0x0,0x4,0x0,0x0,0x4,0x14,0x600,0x0,0x0,0x614,0x0,0x14,0x0,0x0,0x14,0x0,0x0,0x0,0x2617,0x0,0x0,0x2617,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public SacParser(CharStream stream) {
    token_source = new SacParserTokenManager(stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 123; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(CharStream stream) {
    token_source.ReInit(stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 123; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public SacParser(SacParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 123; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(SacParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 123; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    return (jj_scanpos.kind != kind);
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private List<int[]> jj_expentries = new ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      
        for(int[] oldentry : jj_expentries) {
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[97];
    for (int i = 0; i < 97; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 123; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 97; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 2; i++) {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
          }
        }
        p = p.next;
      } while (p != null);
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
